=== hemanth3006/NCP/vgsales.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace = "localfile" xmlns = "localfile" elementFormDefault = "qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="row" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:short" name="Rank"/>
              <xs:element type="xs:string" name="Name"/>
              <xs:element type="xs:string" name="Platform"/>
              <xs:element type="xs:string" name="Year"/>
              <xs:element type="xs:string" name="Genre"/>
              <xs:element type="xs:string" name="Publisher"/>
              <xs:element type="xs:float" name="NA_Sales"/>
              <xs:element type="xs:float" name="EU_Sales"/>
              <xs:element type="xs:float" name="JP_Sales"/>
              <xs:element type="xs:float" name="Other_Sales"/>
              <xs:element type="xs:float" name="Global_Sales"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hemanth3006/NCP/vgsales.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="localfile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "localfile vgsales.xsd">
  <row>
    <Rank>1</Rank>
    <Name>Wii Sports</Name>
    <Platform>Wii</Platform>
    <Year>2006</Year>
    <Genre>Sports</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>41.49</NA_Sales>
    <EU_Sales>29.02</EU_Sales>
    <JP_Sales>3.77</JP_Sales>
    <Other_Sales>8.46</Other_Sales>
    <Global_Sales>82.74</Global_Sales>
  </row>
  <row>
    <Rank>2</Rank>
    <Name>Super Mario Bros.</Name>
    <Platform>NES</Platform>
    <Year>1985</Year>
    <Genre>Platform</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>29.08</NA_Sales>
    <EU_Sales>3.58</EU_Sales>
    <JP_Sales>6.81</JP_Sales>
    <Other_Sales>0.77</Other_Sales>
    <Global_Sales>40.24</Global_Sales>
  </row>
  <row>
    <Rank>3</Rank>
    <Name>Mario Kart Wii</Name>
    <Platform>Wii</Platform>
    <Year>2008</Year>
    <Genre>Racing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>15.85</NA_Sales>
    <EU_Sales>12.88</EU_Sales>
    <JP_Sales>3.79</JP_Sales>
    <Other_Sales>3.31</Other_Sales>
    <Global_Sales>35.82</Global_Sales>
  </row>
  <row>
    <Rank>4</Rank>
    <Name>Wii Sports Resort</Name>
    <Platform>Wii</Platform>
    <Year>2009</Year>
    <Genre>Sports</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>15.75</NA_Sales>
    <EU_Sales>11.01</EU_Sales>
    <JP_Sales>3.28</JP_Sales>
    <Other_Sales>2.96</Other_Sales>
    <Global_Sales>33</Global_Sales>
  </row>
  <row>
    <Rank>5</Rank>
    <Name>Pokemon Red/Pokemon Blue</Name>
    <Platform>GB</Platform>
    <Year>1996</Year>
    <Genre>Role-Playing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>11.27</NA_Sales>
    <EU_Sales>8.89</EU_Sales>
    <JP_Sales>10.22</JP_Sales>
    <Other_Sales>1</Other_Sales>
    <Global_Sales>31.37</Global_Sales>
  </row>
  <row>
    <Rank>6</Rank>
    <Name>Tetris</Name>
    <Platform>GB</Platform>
    <Year>1989</Year>
    <Genre>Puzzle</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>23.2</NA_Sales>
    <EU_Sales>2.26</EU_Sales>
    <JP_Sales>4.22</JP_Sales>
    <Other_Sales>0.58</Other_Sales>
    <Global_Sales>30.26</Global_Sales>
  </row>
  <row>
    <Rank>7</Rank>
    <Name>New Super Mario Bros.</Name>
    <Platform>DS</Platform>
    <Year>2006</Year>
    <Genre>Platform</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>11.38</NA_Sales>
    <EU_Sales>9.23</EU_Sales>
    <JP_Sales>6.5</JP_Sales>
    <Other_Sales>2.9</Other_Sales>
    <Global_Sales>30.01</Global_Sales>
  </row>
  <row>
    <Rank>8</Rank>
    <Name>Wii Play</Name>
    <Platform>Wii</Platform>
    <Year>2006</Year>
    <Genre>Misc</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>14.03</NA_Sales>
    <EU_Sales>9.2</EU_Sales>
    <JP_Sales>2.93</JP_Sales>
    <Other_Sales>2.85</Other_Sales>
    <Global_Sales>29.02</Global_Sales>
  </row>
  <row>
    <Rank>9</Rank>
    <Name>New Super Mario Bros. Wii</Name>
    <Platform>Wii</Platform>
    <Year>2009</Year>
    <Genre>Platform</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>14.59</NA_Sales>
    <EU_Sales>7.06</EU_Sales>
    <JP_Sales>4.7</JP_Sales>
    <Other_Sales>2.26</Other_Sales>
    <Global_Sales>28.62</Global_Sales>
  </row>
  <row>
    <Rank>10</Rank>
    <Name>Duck Hunt</Name>
    <Platform>NES</Platform>
    <Year>1984</Year>
    <Genre>Shooter</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>26.93</NA_Sales>
    <EU_Sales>0.63</EU_Sales>
    <JP_Sales>0.28</JP_Sales>
    <Other_Sales>0.47</Other_Sales>
    <Global_Sales>28.31</Global_Sales>
  </row>
  <row>
    <Rank>11</Rank>
    <Name>Nintendogs</Name>
    <Platform>DS</Platform>
    <Year>2005</Year>
    <Genre>Simulation</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>9.07</NA_Sales>
    <EU_Sales>11</EU_Sales>
    <JP_Sales>1.93</JP_Sales>
    <Other_Sales>2.75</Other_Sales>
    <Global_Sales>24.76</Global_Sales>
  </row>
  <row>
    <Rank>12</Rank>
    <Name>Mario Kart DS</Name>
    <Platform>DS</Platform>
    <Year>2005</Year>
    <Genre>Racing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>9.81</NA_Sales>
    <EU_Sales>7.57</EU_Sales>
    <JP_Sales>4.13</JP_Sales>
    <Other_Sales>1.92</Other_Sales>
    <Global_Sales>23.42</Global_Sales>
  </row>
  <row>
    <Rank>13</Rank>
    <Name>Pokemon Gold/Pokemon Silver</Name>
    <Platform>GB</Platform>
    <Year>1999</Year>
    <Genre>Role-Playing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>9</NA_Sales>
    <EU_Sales>6.18</EU_Sales>
    <JP_Sales>7.2</JP_Sales>
    <Other_Sales>0.71</Other_Sales>
    <Global_Sales>23.1</Global_Sales>
  </row>
  <row>
    <Rank>14</Rank>
    <Name>Wii Fit</Name>
    <Platform>Wii</Platform>
    <Year>2007</Year>
    <Genre>Sports</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>8.94</NA_Sales>
    <EU_Sales>8.03</EU_Sales>
    <JP_Sales>3.6</JP_Sales>
    <Other_Sales>2.15</Other_Sales>
    <Global_Sales>22.72</Global_Sales>
  </row>
  <row>
    <Rank>15</Rank>
    <Name>Wii Fit Plus</Name>
    <Platform>Wii</Platform>
    <Year>2009</Year>
    <Genre>Sports</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>9.09</NA_Sales>
    <EU_Sales>8.59</EU_Sales>
    <JP_Sales>2.53</JP_Sales>
    <Other_Sales>1.79</Other_Sales>
    <Global_Sales>22</Global_Sales>
  </row>
  <row>
    <Rank>16</Rank>
    <Name>Kinect Adventures!</Name>
    <Platform>X360</Platform>
    <Year>2010</Year>
    <Genre>Misc</Genre>
    <Publisher>Microsoft Game Studios</Publisher>
    <NA_Sales>14.97</NA_Sales>
    <EU_Sales>4.94</EU_Sales>
    <JP_Sales>0.24</JP_Sales>
    <Other_Sales>1.67</Other_Sales>
    <Global_Sales>21.82</Global_Sales>
  </row>
  <row>
    <Rank>17</Rank>
    <Name>Grand Theft Auto V</Name>
    <Platform>PS3</Platform>
    <Year>2013</Year>
    <Genre>Action</Genre>
    <Publisher>Take-Two Interactive</Publisher>
    <NA_Sales>7.01</NA_Sales>
    <EU_Sales>9.27</EU_Sales>
    <JP_Sales>0.97</JP_Sales>
    <Other_Sales>4.14</Other_Sales>
    <Global_Sales>21.4</Global_Sales>
  </row>
  <row>
    <Rank>18</Rank>
    <Name>Grand Theft Auto: San Andreas</Name>
    <Platform>PS2</Platform>
    <Year>2004</Year>
    <Genre>Action</Genre>
    <Publisher>Take-Two Interactive</Publisher>
    <NA_Sales>9.43</NA_Sales>
    <EU_Sales>0.4</EU_Sales>
    <JP_Sales>0.41</JP_Sales>
    <Other_Sales>10.57</Other_Sales>
    <Global_Sales>20.81</Global_Sales>
  </row>
  <row>
    <Rank>19</Rank>
    <Name>Super Mario World</Name>
    <Platform>SNES</Platform>
    <Year>1990</Year>
    <Genre>Platform</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>12.78</NA_Sales>
    <EU_Sales>3.75</EU_Sales>
    <JP_Sales>3.54</JP_Sales>
    <Other_Sales>0.55</Other_Sales>
    <Global_Sales>20.61</Global_Sales>
  </row>
  <row>
    <Rank>20</Rank>
    <Name>Brain Age: Train Your Brain in Minutes a Day</Name>
    <Platform>DS</Platform>
    <Year>2005</Year>
    <Genre>Misc</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>4.75</NA_Sales>
    <EU_Sales>9.26</EU_Sales>
    <JP_Sales>4.16</JP_Sales>
    <Other_Sales>2.05</Other_Sales>
    <Global_Sales>20.22</Global_Sales>
  </row>
  <row>
    <Rank>21</Rank>
    <Name>Pokemon Diamond/Pokemon Pearl</Name>
    <Platform>DS</Platform>
    <Year>2006</Year>
    <Genre>Role-Playing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>6.42</NA_Sales>
    <EU_Sales>4.52</EU_Sales>
    <JP_Sales>6.04</JP_Sales>
    <Other_Sales>1.37</Other_Sales>
    <Global_Sales>18.36</Global_Sales>
  </row>
  <row>
    <Rank>22</Rank>
    <Name>Super Mario Land</Name>
    <Platform>GB</Platform>
    <Year>1989</Year>
    <Genre>Platform</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>10.83</NA_Sales>
    <EU_Sales>2.71</EU_Sales>
    <JP_Sales>4.18</JP_Sales>
    <Other_Sales>0.42</Other_Sales>
    <Global_Sales>18.14</Global_Sales>
  </row>
  <row>
    <Rank>23</Rank>
    <Name>Super Mario Bros. 3</Name>
    <Platform>NES</Platform>
    <Year>1988</Year>
    <Genre>Platform</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>9.54</NA_Sales>
    <EU_Sales>3.44</EU_Sales>
    <JP_Sales>3.84</JP_Sales>
    <Other_Sales>0.46</Other_Sales>
    <Global_Sales>17.28</Global_Sales>
  </row>
  <row>
    <Rank>24</Rank>
    <Name>Grand Theft Auto V</Name>
    <Platform>X360</Platform>
    <Year>2013</Year>
    <Genre>Action</Genre>
    <Publisher>Take-Two Interactive</Publisher>
    <NA_Sales>9.63</NA_Sales>
    <EU_Sales>5.31</EU_Sales>
    <JP_Sales>0.06</JP_Sales>
    <Other_Sales>1.38</Other_Sales>
    <Global_Sales>16.38</Global_Sales>
  </row>
  <row>
    <Rank>25</Rank>
    <Name>Grand Theft Auto: Vice City</Name>
    <Platform>PS2</Platform>
    <Year>2002</Year>
    <Genre>Action</Genre>
    <Publisher>Take-Two Interactive</Publisher>
    <NA_Sales>8.41</NA_Sales>
    <EU_Sales>5.49</EU_Sales>
    <JP_Sales>0.47</JP_Sales>
    <Other_Sales>1.78</Other_Sales>
    <Global_Sales>16.15</Global_Sales>
  </row>
  <row>
    <Rank>26</Rank>
    <Name>Pokemon Ruby/Pokemon Sapphire</Name>
    <Platform>GBA</Platform>
    <Year>2002</Year>
    <Genre>Role-Playing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>6.06</NA_Sales>
    <EU_Sales>3.9</EU_Sales>
    <JP_Sales>5.38</JP_Sales>
    <Other_Sales>0.5</Other_Sales>
    <Global_Sales>15.85</Global_Sales>
  </row>
  <row>
    <Rank>27</Rank>
    <Name>Pokemon Black/Pokemon White</Name>
    <Platform>DS</Platform>
    <Year>2010</Year>
    <Genre>Role-Playing</Genre>
    <Publisher>Nintendo</Publisher>
    <NA_Sales>5.57</NA_Sales>
    <EU_Sales>3.28</EU_Sales>
